# fly.toml app configuration file generated for n8n-flyio-awesomejerry on 2025-06-21T11:58:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-flyio-awesomejerry'
primary_region = 'sin'

[build]
  image = "n8nio/n8n:latest"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = true
  N8N_RUNNERS_ENABLED = true
  WEBHOOK_URL = 'https://n8n-flyio-awesomejerry.fly.dev'
  GENERIC_TIMEZONE = 'Asia/Taipei'
  TZ = 'Asia/Taipei'
  N8N_CUSTOM_EXTENSIONS = '/home/node/.n8n/custom-extensions/node_modules'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
